---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/13 15:48
---
a = true
b = false
--逻辑与
print(a and b)
--逻辑或
print(a or b)
--逻辑非
print(not a)
--字符串连接
print('小仙女'..'薇儿')
--计算字符串个数
print(#'挨操小仙女儿')

-- == ，判断是否相等，比较的是值！！！
a = 'nigger'
b = 'nigger'
print('nigger' == 'nigger')
print(a == b)
-- ~=，判断是否不相等
print('xiannv' ~= 'saobi')
print(a ~= b)