---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/11/13 16:27
---
table1 = {}
table1[1] = 'nigger'
print(table1[1])
table1[1] = nil
print(table1[1],table1[2])

